{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "monstache.fullname" . }}
  labels:
    {{- include "monstache.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.count }}
  selector:
    matchLabels:
      {{- include "monstache.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "monstache.fullname" . }}
  volumeClaimTemplates: []
  template:
    metadata:
      labels:
        {{- include "monstache.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "monstache.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: monstache-config
          configMap:
            name: {{ include "monstache.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
            {{- if $.Values.worker.enabled }}
            - name: MONSTACHE_WORKER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- end -}}
          {{- end }}
          args:
          - --enable-http-server
          - -f
          - /etc/monstache/config.toml
          volumeMounts:
            - mountPath: /etc/monstache/config.toml
              name: monstache-config
              subPath: config.toml
            - mountPath: /etc/monstache/transforms
              name: monstache-config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}